name: Publish to Github Pages
on: [workflow_dispatch]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'martinussuherman'
        reponame: 'vuetify-material-dashboard'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
